name: "Build"
on:
  push:
    branches:
      - "4.x"
    tags:
      - v4*
  pull_request:
    branches:
      - "4.x"
    types: [opened, reopened, synchronize]

jobs:
  build:
    strategy:
       matrix:
          node: [ 14, 16 ]
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn
      - run: ./scripts/download_geth.sh
      - run: tar -czvf /tmp/web3.js.tar.gz --exclude="./.git" ./
      - run: tar -czvf /tmp/cache.js.tar.gz /home/runner/.cache
      - uses: actions/upload-artifact@v3
        with:
          name: web3-${{ matrix.node }}.js.tar.gz
          path: |
              /tmp/web3.js.tar.gz
              /tmp/cache.js.tar.gz

  lint:
    name: lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: web3-${{ matrix.node }}.js.tar.gz
          path: /tmp
      - run: tar -xf /tmp/web3.js.tar.gz -C ./
      - run: tar -xf /tmp/cache.js.tar.gz -C /home/runner/.cache
      - run: yarn lint

  unit:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16 ]
    steps:
      - uses: actions/download-artifact@v3
        with:
            name: web3-${{ matrix.node }}.js.tar.gz
            path: /tmp
      - run: tar -xf /tmp/web3.js.tar.gz -C ./
      - run: tar -xf /tmp/cache.js.tar.gz -C /home/runner/.cache
      - run: yarn test:unit

  integration:
    name: Integration
    needs: unit
    runs-on: ubuntu-latest
    env:
        INFURA_GOERLI_HTTP: ${{ secrets.INFURA_GOERLI_HTTP }}
        INFURA_GOERLI_WS: ${{ secrets.INFURA_GOERLI_WS }}
    strategy:
      fail-fast: false
      matrix:
        node: [ 14, 16 ]
        backend: ['geth', 'ganache']
        mode: ['http', 'ws']
    steps:
      - uses: actions/download-artifact@v3
        with:
            name: web3-${{ matrix.node }}.js.tar.gz
            path: /tmp
      - run: tar -xf /tmp/web3.js.tar.gz -C ./
      - run: tar -xf /tmp/cache.js.tar.gz -C /home/runner/.cache
      - run: yarn test:e2e:${{ matrix.backend }}:${{ matrix.mode }}
        shell: bash

  e2e:
    name: End-to-End
    needs: unit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 14, 16 ]
        browser: ['electron', 'chrome', 'firefox','ipc']
    steps:
      - uses: actions/download-artifact@v3
        with:
            name: web3-${{ matrix.node }}.js.tar.gz
            path: /tmp
      - run: tar -xf /tmp/web3.js.tar.gz -C ./
      - run: tar -xf /tmp/cache.js.tar.gz -C /home/runner/.cache
      - run: yarn test:e2e:ganache:ws:${{ matrix.browser }}
        shell: bash
